# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Merqantile
                                 A QGIS plugin
 Easy visualisation of XYZ tile bounds
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-11
        copyright            : (C) 2024 by zabop
        email                : merqantile.sixtyfold818@passmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'zabop'
__date__ = '2024-08-11'
__copyright__ = '(C) 2024 by zabop'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Merqantile class from file Merqantile.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .merqantile import MerqantilePlugin
    return MerqantilePlugin()
