on:
    release:
      types: published
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: 3.12
  
        - name: Install qgis-plugin-ci
          run: pip3 install qgis-plugin-ci

        - name: Deploy plugin
          run: >-
            qgis-plugin-ci \
            release --release-tag ${GITHUB_REF/refs\/tags\//} \
            --osgeo-username "$OSGEO_USER" \
            --osgeo-password "$OSGEO_PASSWORD" \
            ${GITHUB_REF/refs\/tags\//}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OSGEO_USER: ${{ secrets.OSGEO_USER }}
            OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}